### ISSUE TITLE
ContactsWrapper returning undefined

### ISSUE THREAD

**Issue by micopc** [LynxITDigital/react-native-contacts-wrapper-example#1]
Hi,

I setup the package the way you explained and made a build on Android. But
 import ContactsWrapper from 'react-native-contacts-wrapper'; is returning undefined.

Testing on emulator, API 22.

Is there some thing else I need to do before using the package?

**Comment by marko89kv** [comment]
Did you link it? I linked it, but now the app cannot be compiled.

**Comment by decoderzhub** [comment]
I'm having the same issue:
error: package com.lynxit.contactswrapper does not exist
import com.lynxit.contactswrapper.ContactsWrapperPackage;

I've been messing with this for hours now.  It's not even showing up in the node modules and I've had to comment out:

dependencies {
    // compile project(':react-native-contacts-wrapper')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}

the dependency to even make it through the compile or else I get this error:
- What went wrong:
  A problem occurred configuring project ':app'.
  > Cannot evaluate module react-native-contacts-wrapper : Configuration with name 'default' not found.

Please fix this soon

**Comment by decoderzhub** [comment]
I found the issue for this on my other account devgroup1 I posted what needs to be fixed I hope this helps any future developer.
@devgroup1
[https://github.com/LynxITDigital/react-native-contacts-wrapper/issues/10](url)

**Comment by micopc** [comment]
Sorry for the lack of responses, but I ended up copying the code found in react-native-contacts-wrapper to a java module created by me and importing it.
